sudo: false
cache:
  directories:
    - $HOME/.cache/pip

language: python


matrix:
  include:
    - python: "2.7"
      env: TOXENV=py27-pyopenssl015-idna
    - python: "2.7"
      env: TOXENV=py27-pyopenssl015-noidna
    - python: "2.7"
      env: TOXENV=py27-pyopenssl014-idna
    - python: "2.7"
      env: TOXENV=py27-pyopenssl014-noidna
    - python: "2.7"
      env: TOXENV=py27-pyopenssl16-idna
    - python: "2.7"
      env: TOXENV=py27-pyopenssl16-noidna
    - python: "2.7"
      env: TOXENV=py27-pyopensslLatest-idna
    - python: "2.7"
      env: TOXENV=py27-pyopensslLatest-noidna
    - python: "3.4"
      env: TOXENV=py34-pyopenssl015-idna
    - python: "3.4"
      env: TOXENV=py34-pyopenssl015-noidna
    - python: "3.4"
      env: TOXENV=py34-pyopenssl014-idna
    - python: "3.4"
      env: TOXENV=py34-pyopenssl014-noidna
    - python: "3.4"
      env: TOXENV=py34-pyopenssl16-idna
    - python: "3.4"
      env: TOXENV=py34-pyopenssl16-noidna
    - python: "3.4"
      env: TOXENV=py34-pyopensslLatest-idna
    - python: "3.4"
      env: TOXENV=py34-pyopensslLatest-noidna
    - python: "3.5"
      env: TOXENV=py35-pyopenssl015-idna
    - python: "3.5"
      env: TOXENV=py35-pyopenssl015-noidna
    - python: "3.5"
      env: TOXENV=py35-pyopenssl014-idna
    - python: "3.5"
      env: TOXENV=py35-pyopenssl014-noidna
    - python: "3.5"
      env: TOXENV=py35-pyopenssl16-idna
    - python: "3.5"
      env: TOXENV=py35-pyopenssl16-noidna
    - python: "3.5"
      env: TOXENV=py35-pyopensslLatest-idna
    - python: "3.5"
      env: TOXENV=py35-pyopensslLatest-noidna
    - python: "3.6"
      env: TOXENV=py36-pyopenssl015-idna
    - python: "3.6"
      env: TOXENV=py36-pyopenssl015-noidna
    - python: "3.6"
      env: TOXENV=py36-pyopenssl014-idna
    - python: "3.6"
      env: TOXENV=py36-pyopenssl014-noidna
    - python: "3.6"
      env: TOXENV=py36-pyopenssl16-idna
    - python: "3.6"
      env: TOXENV=py36-pyopenssl16-noidna
    - python: "3.6"
      env: TOXENV=py36-pyopensslLatest-idna
    - python: "3.6"
      env: TOXENV=py36-pyopensslLatest-noidna
    - python: "pypy"
      env: TOXENV=pypy-pyopenssl015-idna
    - python: "pypy"
      env: TOXENV=pypy-pyopenssl015-noidna
    - python: "pypy"
      env: TOXENV=pypy-pyopenssl014-idna
    - python: "pypy"
      env: TOXENV=pypy-pyopenssl014-noidna
    - python: "pypy"
      env: TOXENV=pypy-pyopenssl16-idna
    - python: "pypy"
      env: TOXENV=pypy-pyopenssl16-noidna
    - python: "pypy"
      env: TOXENV=pypy-pyopensslLatest-idna
    - python: "pypy"
      env: TOXENV=pypy-pyopensslLatest-noidna

    # Meta
    - python: "3.5"
      env: TOXENV=flake8
    - python: "3.5"
      env: TOXENV=manifest
    - python: "3.5"
      env: TOXENV=docs
    - python: "3.5"
      env: TOXENV=readme


install:
  - |
    if [[ "${TOXENV}" = pypy* ]]; then
        git clone --depth 1 https://github.com/yyuu/pyenv.git ~/.pyenv
        PYENV_ROOT="$HOME/.pyenv"
        PATH="$PYENV_ROOT/bin:$PATH"
        eval "$(pyenv init -)"
        pyenv install pypy-5.6.0
        pyenv global pypy-5.6.0
    fi
  - pip install -U tox


script:
  - |
    # activate the pypy env we installed via our custom pyenv in the install stage
    if [[ "${TOXENV}" == "pypy" ]]; then
        PYENV_ROOT="$HOME/.pyenv"
        PATH="$PYENV_ROOT/bin:$PATH"
        eval "$(pyenv init -)"
    fi
  - tox


before_install:
  - pip install codecov


after_success:
  - tox -e coverage-report
  - codecov
